#define LLS_DELAY 30
#define LLS_QUEUE 10

#undef PERMISSIVE_HOLD
#define RETRO_TAPPING
#undef TAPPING_TERM
#define TAPPING_TERM 300
// #define SPLIT_WATCHDOG_ENABLE
// #define SPLIT_USB_TIMEOUT 5000
